src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="date")
     */
    private $logindate;
    
    /**
     * @ORM\OneToMany(targetEntity=Town::class, mappedBy="user")
     */
    private $Towns;

    /**
     * @ORM\OneToMany(targetEntity=Action::class, mappedBy="user")
     */
    private $actions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isblocked;

    /**
     * @ORM\Column(type="integer")
     */
    private $coins;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $actionCount;

    public function __construct()
    {
        $this->Towns = new ArrayCollection();
        $this->actions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getCoins(): ?int
    {
        return $this->coins;
    }
    public function setCoins(string $coins): self
    {
        $this->coins = $coins;

        return $this;
    }
    public function getActionCount(): ?int
    {
        return $this->actionCount;
    }
    public function setActionCount(string $actionCount): self
    {
        $this->actionCount = $actionCount;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }



    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }


    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getLogindate(): ?\DateTimeInterface
    {
        return $this->logindate;
    }

    public function setLogindate(\DateTimeInterface $logindate): self
    {
        $this->logindate = $logindate;
        
        return $this;
    }
    
    /**
     * @return Collection|Town[]
     */
    public function getTowns(): Collection
    {
        return $this->Towns;
    }

    public function addTown(Town $town): self
    {
        if (!$this->Towns->contains($town)) {
            $this->Towns[] = $town;
            $town->setUser($this);
        }

        return $this;
    }

    public function removeTown(Town $town): self
    {
        if ($this->Towns->removeElement($town)) {
            // set the owning side to null (unless already changed)
            if ($town->getUser() === $this) {
                $town->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Action[]
     */
    public function getActions(): Collection
    {
        return $this->actions;
    }

    public function addAction(Action $action): self
    {
        if (!$this->actions->contains($action)) {
            $this->actions[] = $action;
            $action->setUser($this);
        }

        return $this;
    }

    public function removeAction(Action $action): self
    {
        if ($this->actions->removeElement($action)) {
            // set the owning side to null (unless already changed)
            if ($action->getUser() === $this) {
                $action->setUser(null);
            }
        }

        return $this;
    }

    public function getIsblocked(): ?bool
    {
        return $this->isblocked;
    }

    public function setIsblocked(bool $isblocked): self
    {
        $this->isblocked = $isblocked;

        return $this;
    }
}

templates/_products.html.twig
  {%  if products is defined %}
    {% for product in products %}

      <div class="col-sm-4">



            {% set isSelected = (product.id in app.session.get('selected')|keys) %}
            <div class="tile {% if isSelected %} badge-secondary {% endif %}">
                <h3>{{ product.name }}</h3>
                <img src="{{ asset(product.getPhoto()) }}">
                <div> {{ product.price }} coins</div>


                {% if isSelected %}
                    <a href="?deselect={{ product.id }}" class="btn btn-primary">Deselect</a>
                {% else %}
                    <a href="?select={{ product.id }}" class="btn btn-primary">Select</a>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('app_product_edit', {id: product.id}) }}" class="btn btn-primary">Edit</a>
                {% endif %}
            </div>

        </a>

      </div>
    {% endfor %}
  {% endif %}
{% if error is defined %}
    <div style="margin: auto">
        <h3>
            {{error}}
        </h3>
    </div>
{% endif %}

templates/admin.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello {{ app.user.username }} {% endblock %}
{% block body %}
    <div class="container">

        <div class="jumbotron">
            {% if error is defined %}
            <p style="color:red">    {{ error }} </p>
            {% endif %}
            <div class="example-wrapper">
                <h1>Hello {{ app.user.username }} </h1>

                <div style="text-align: center">
                    <h3>Persoonlijke gegevens</h3>
                    username: {{ app.user.username }} <br>
                    e-mail: {{ app.user.email }} <br>
                    last logindate: {{ app.user.logindate|date('Y-m-d') }}
                </div>
                <div class="example-wrapper">
                    <div style="text-align: center">
                        <h3>Actie panneel</h3>
                        <a href="{{ path('app_admin_userlist') }}" class="btn btn-info">userlist</a><br>
                        <a href="{{ path('app_admin_reset_speelveld') }}" class="btn btn-danger">Reset speelveld</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/admin_resetspeelveld.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <div class="container">
    <div class="jumbotron">
            <p>
              Are you sure you want the reset the grid?
            </p>
            <form method="post" action="/admin/resetspeelveld">
               <h3> Dimensions: </h3>
              Width:  <input type="number"  name="width" value="20" min="10" max="20" required> (min: 10, max: 20)
               <br>
            Height:  <input type="number"  name="height" value="20" min="10" max="50" required> (min: 10, max: 50)
            <br>
                <button type="submit" class="btn-primary" onclick="return confirm('Are you sure?')">Bevestig</button>
                <a href="/admin" class="btn blue">Cancel</a>
            </form>
        </div>
        {{ app.session.set('speelveld',null) }}
    </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

</head>
<body>
{{ include('header.html.twig') }}
{{ include('navbar.html.twig') }}
{% block body %}{% endblock %}
{% block javascripts %}{% endblock %}
{{ include('footer.html.twig') }}
</body>
</html>

templates/basket.html.twig
{% extends "base.html.twig" %}

{% block title %}Shopping Basket{% endblock %}
{% block head %}{% endblock %}
{% block body %}
    <script>
    function closing() {
            let info = document.getElementById("success");
            info.style.setProperty("display", "none");
        }

    </script>

    <div class="container">
        <div class="jumbotron">

            <div class="row center-block">
        {% set success = app.session.get('success') %}
        {% if success is defined and success is not empty %}
            <div class="success" id="success">
                <div class="closing" onclick="closing()">Close X</div>
                <h1 style="color: blue;">Succesful</h1>

                The units were added to your town.

                <br> <br>
            </div>
        {% endif %}

        <h2> Shopping Basket</h2>
        {%  if app.session.get('error') is defined %}
            <p style="color:red">{{ app.session.get('error') }}</p>
        {% endif  %}

            <div class="row justify-content-sm-center">

               You currently have
                <b> {{ app.user.coins }}  </b>coins in your wallet

            </div>
            <div class="row justify-content-sm-center">

                {% if products is defined and products is not empty %}
                    <table>

                        {% for key, product in products %}

                        <tr>

                            {# <td>                                                 #}
                            {#    <img src="{{ asset(product.getPhoto()) }}">         #}
                            {# </td>                                                    #}
                            <tr>
                                <td>
                                    <tr>
                                    <img src="{{ asset(product.getPhoto()) }}">
                                    </tr>
                                    {{ product.name }} -
                           <b>
                                    {{ product.price }} coins </b>
                                    <form action="/Units/chooseTown" method="post">
                                        <Br>

                                        Koop 20 units voor het volgende dorp:
                                        <input type="hidden" name="productId" value="{{ product.id }}">
                                        <select name="chosenTown" id="chosenTown">
                                            {% for town in app.user.towns %}
                                                <option value="{{ town.id }}">
                                                    Town {{ town.id }} ({{ town.townquantity }}
                                                    units)
                                                </option>
                                            {% endfor %}
                                        </select>
                                       
                                        <br><br>
                                        {% if app.user.towns|length > 0  %}
                                        <input type="submit" class="btn btn-primary" id="confirm" value="Place Order">
                                    {% else %}
                                        You don't have a town yet.
                                        {%  endif %}
                                    </form>

                                </td>


                                    <tr>
                                       {#  <td><a href="{{ path('app_delete_from_basket', {id: key}) }}">remove</a>


                                        </td>#}
                                    </tr>
                        </tr>

                        {% endfor %}
                    </table>







            </div>
            <a href="{{ path('app_clear_basket') }}">Empty basket</a>
            <br>

            {% else %}
            <div>
<br>
                <b>Make a selection in the <a href="{{ path('app_product')}}">shop </a></b>
            </div>
        </div>

        {% endif %}



        </div>  </div>
    </div>
    {{  app.session.remove("success")  }}
    {{  app.session.remove("error")  }}
{% endblock %}

templates/create_grid.html.twig
{#{{ dump(locations) }}#}

<table>
   {% for row in locations %}
        <tr>
            {% for col in row %}
                <td>{{ col }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>

templates/footer.html.twig
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="text-center" style="background-color: #e7302a;">
        <div class="row">
            <div class="col">
                <h3>Disclaimer</h3>
            </div>
        </div>

        <br>
        <div style="color:white">
            <small>Copyright &copy; Team Blu Website</small>
        </div>
        <br>
    </div>

</footer>

templates/header.html.twig
     <div class="navbar-header" style="display:block;background-image:url({{ asset('images/bannerbackground.png') }}); resize: vertical; width:100%">
         <div style="resize: none;  margin:auto">
          <a href="{{ path('app_home') }}" >
               <img src="{{ asset('images/banner.png') }}" alt="tribalwars.">
          </a>
         </div>
     </div>

templates/navbar.html.twig
<div>
    <nav class="nav justify-content-center " role="navigation">
    {% set section = app.request.get('section') %}
    <div class="navigation"><a class="nav-link {{ section  == 'home' ? 'btn-default' : '' }}" href="{{ path('app_home')}}"> Join Game </a>
        <a> | </a>
        <a class="nav-link {{ section  == 'rules' ? 'btn-default' : '' }}" href="{{ path('app_rules')}}"> Rules of the Game </a>
        <a> | </a>
        {% if app.user %}

            <a class="nav-link" href="{{ path('app_profile') }}">
               Profile  </a>
            <a> | </a>
            <a class="nav-link {{ section  == 'product' ? 'btn-default' : '' }}" href="{{ path('app_product')}}"> Shop </a>
            <a> | </a>
            <a class="nav-link {{ section  == 'basket' ? 'btn-default' : '' }}" href="{{ path('app_basket') }}">Shopping Basket</a>
            {% if is_granted('ROLE_ADMIN') %}
                <a> | </a>
                <a class="navbar-link" {{ section  == 'admin' ? 'btn-default' : '' }} href="{{ path('app_admin') }}">Adminpanel</a>
            {% endif %}

            <a> | </a>
            <a class="nav-link" href="{{ path('app_logout') }}">
                Logout </a>

        {% else %}
            <a class="nav-link {{ section  == 'login' ? 'btn-default' : '' }}" href="{{ path('app_login')}}"> Log In </a>

        {% endif %}

    </div>
    </nav>
</div>

templates/product.html.twig
{% extends "base.html.twig" %}

{% block title %}Shop{% endblock %}
{% block head %}{% endblock %}
{% block body %}



    <div class="container">


        <div class="jumbotron">

            <h2> Shop </h2>
            {% if app.session.get('selected')|keys %}
                <a href="{{ path('app_add_to_basket') }}", style="color:white" class="btn btn-danger">Add selected products to cart</a>
            {% endif %}


            <div class="row" id="products">
                {% include '_products.html.twig' %}
            </div>


            <br>
        </div>

    </div>
{% endblock %}

templates/productdetail.html.twig
{% extends "base.html.twig" %}

{% block title %}Productcatalogus{% endblock %}
{% block head %}{% endblock %}
{% block body %}


    <div class="container">
        <h2> Onze producten</h2>

        <div class="jumbotron">

            <div class="card" id="card">


                    <div class="card-header">
                        <h3>Product Detail: {{ product.name }}</h3>
                        </div>
                <div class="card-img">
                        <img src="{{ asset(product.getPhoto()) }}">
                    </div>

                <div class="card-body">
                    <h4>Description</h4>
                    <div> Description </div>
                    <div> Prijs: {{ product.price }} </div>
                    <div>
                    <a href="{{ path('app_add_to_basket', {id: product.id}) }}" class="btn btn-primary">Add to Cart</a>
                        {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('app_product_edit', {id: product.id}) }}" class="btn btn-warning">Edit</a>
                        {% endif %}
                    </div>

                </div>


            </div>

        </div>


    <a href="{{ path('app_product') }}" class="btn btn-primary">Back</a>
        <br></br>
    </div>
{% endblock %}

templates/productedit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edit Character{% endblock %}
{% block head %}{% endblock %}
{% block body %}


    <div class="container">
        <h2> Edit following item: {{ product.name }}</h2>
<div class="align-items-sm-center" >
    <div style="width:500px;margin:auto">

    {{ form(form) }}
    </div>
        </div>

        {% if is_granted('ROLE_ADMIN') %}
            <a href="{{ path('app_admin') }}">Back</a>
        {% else %}
            <a href="{{ path('app_product') }}" class="btn btn-primary">Back</a>
        {% endif %}
        <br></br>
    </div>
{% endblock %}

templates/rules.html.twig
{% extends "base.html.twig" %}

{% block title %}Home{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron">
            <custom>Official Game Rules</custom>
            <br><hr>

            <h3> Voor nieuwe spelers:</h3>
                    <div>
                        Je kan gratis een town ter waarde van 20 units bouwen.
                    </div>

                    <h3>Town Bouwen:</h3>

                    <div>
                        Het bouwen van een town kost 20 units <br>
                        Let op: je mag niet onmiddellijk naast een town van een tegenspeler bouwen, je moet altijd een
                        speelveld tussen laten
                    </div>

                    <h3>Town Veroveren:</h3>

                    <div>
                        Je mag kiezen hoeveel units je van je town verstuurt naar de town van je tegenspeler
                        Let op: per speelveld tussen jouw town en de town van je tegenspeler verlies je procentueel
                        een aantal units of basis van de afstand tussen de twee towns.

                        Als je de town van je tegenspeler weet te bereiken met een aantal units, dan volgt er een spannende strijd.
                        Er komt hier voor een deel geluk bij kijken maar aan te raden is dat je altijd tenminste ongeveer evenveel units moet sturen om een town te veroveren.
                        De verliezer van de confrontatie verliest al zijn eenheden, dus denk goed na voordat je jouw eenheden op pad stuurt.
                    </div>

                    <h3>Town Verdedigen:</h3>

                    <div>
                        Je kan er ook voor kiezen om je een town strategisch te versterken door er een aantal units van één van je andere towns naar te
                        sturen.
                        Let op: Je kan hier ook eenheden verliezen afhankelijk van de afstand tussen je towns. Bouw ze dus niet te ver uit elkaar.
                    </div>
            <h3>Coins:</h3>
            <div>
            Per 20 acties die je onderneemt krijg je 5 coins. Met deze coins kan je units kopen en naar één van je dorpen sturen.
            </div>
                    <br>
            <h3>Bonus:</h3>
                    <div>
                        Je krijgt elke dag automatisch 10 extra units per town die je runt. Hiervoor moet je helemaal niets doen. Als je daarboven ook elke dag inlogt, krijg je nog eens 4 units extra erbij per town.
                        Je towns dagelijks in de gaten houden loont dus!
                    </div>

                    <div>
                        <br>
                        <a href="{{ path('app_home') }}">Back</a>
                    </div>

        </div>
    </div>
{% endblock %}